### ISSUE TITLE
The `.bin/index.js` is not available in the NPM package

### ISSUE THREAD

**Issue by ThaNarie** [camacho/install-deps-postmerge#1]
https://github.com/camacho/install-deps-postmerge/blob/17dc911f9331379c17d208e829409b1b7c971ab7/package.json#L18

Maybe auto-ignored when packaging/publishing?

**Comment by manuelbieh** [comment]
Have the same issue here. 

```
error Command "install-deps-postmerge" not found.
```

And I don't have a `install-deps-postmerge` in `node_modules/.bin` when I clone a fresh version of a project I've successfully been using it in for months now.

**Comment by manuelbieh** [comment]
Looks like a yarn issue. When installed via `npm install` I have the file in the `node_modules/.bin` folder

**Comment by manuelbieh** [comment]
Sorry for the spam. This bug was apparently introduced in Yarn 1.12.3. It works fine with 1.12.1. I created an issue already: https://github.com/yarnpkg/yarn/issues/6844

**Comment by camacho** [comment]
thanks for bringing this up! @ThaNarie are you also using a newer version of Yarn?

**Comment by ThaNarie** [comment]
@camacho Yes I have Yarn version `1.12.3` installed.
